"""add performance indexes and cascading  via models

Revision ID: 42b2dd45c406
Revises: 5ba3442501a3
Create Date: 2025-07-22 19:57:23.855992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b2dd45c406'
down_revision: Union[str, Sequence[str], None] = '5ba3442501a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admins_library_id'), 'admins', ['library_id'], unique=False)
    op.create_index(op.f('ix_admins_role'), 'admins', ['role'], unique=False)
    op.create_index(op.f('ix_admins_status'), 'admins', ['status'], unique=False)
    op.drop_constraint(op.f('admins_library_id_fkey'), 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_libraries_name'), 'libraries', ['name'], unique=False)
    op.alter_column('monthly_payments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_payments_library_month', 'monthly_payments', ['library_id', 'month'], unique=False)
    op.create_index('idx_payments_library_paid', 'monthly_payments', ['library_id', 'paid'], unique=False)
    op.create_index('idx_payments_student_month', 'monthly_payments', ['student_id', 'month'], unique=False)
    op.create_index(op.f('ix_monthly_payments_library_id'), 'monthly_payments', ['library_id'], unique=False)
    op.create_index(op.f('ix_monthly_payments_paid'), 'monthly_payments', ['paid'], unique=False)
    op.create_index(op.f('ix_monthly_payments_student_id'), 'monthly_payments', ['student_id'], unique=False)
    op.drop_constraint(op.f('monthly_payments_student_id_fkey'), 'monthly_payments', type_='foreignkey')
    op.drop_constraint(op.f('monthly_payments_library_id_fkey'), 'monthly_payments', type_='foreignkey')
    op.create_foreign_key(None, 'monthly_payments', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'monthly_payments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_seats_library_number', 'seats', ['library_id', 'seat_number'], unique=False)
    op.create_index(op.f('ix_seats_library_id'), 'seats', ['library_id'], unique=False)
    op.create_index(op.f('ix_seats_seat_number'), 'seats', ['seat_number'], unique=False)
    op.create_index(op.f('ix_seats_shift1_student_id'), 'seats', ['shift1_student_id'], unique=False)
    op.create_index(op.f('ix_seats_shift2_student_id'), 'seats', ['shift2_student_id'], unique=False)
    op.create_index(op.f('ix_seats_shift3_student_id'), 'seats', ['shift3_student_id'], unique=False)
    op.drop_constraint(op.f('seats_shift1_student_id_fkey'), 'seats', type_='foreignkey')
    op.drop_constraint(op.f('seats_library_id_fkey'), 'seats', type_='foreignkey')
    op.drop_constraint(op.f('seats_shift3_student_id_fkey'), 'seats', type_='foreignkey')
    op.drop_constraint(op.f('seats_shift2_student_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seats', 'students', ['shift1_student_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'seats', 'students', ['shift3_student_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'seats', 'students', ['shift2_student_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_students_library_status', 'students', ['library_id', 'status'], unique=False)
    op.create_index(op.f('ix_students_contact'), 'students', ['contact'], unique=False)
    op.create_index(op.f('ix_students_date_of_joining'), 'students', ['date_of_joining'], unique=False)
    op.create_index(op.f('ix_students_library_id'), 'students', ['library_id'], unique=False)
    op.create_index(op.f('ix_students_seat_id'), 'students', ['seat_id'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.drop_constraint(op.f('students_library_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_seat_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'seats', ['seat_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_seat_id_fkey', 'students', type_='foreignkey')
    op.drop_constraint('students_library_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_seat_id_fkey'), 'students', 'seats', ['seat_id'], ['id'])
    op.create_foreign_key(op.f('students_library_id_fkey'), 'students', 'libraries', ['library_id'], ['id'])
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_seat_id'), table_name='students')
    op.drop_index(op.f('ix_students_library_id'), table_name='students')
    op.drop_index(op.f('ix_students_date_of_joining'), table_name='students')
    op.drop_index(op.f('ix_students_contact'), table_name='students')
    op.drop_index('idx_students_library_status', table_name='students')
    op.drop_constraint('seats_shift2_student_id_fkey', 'seats', type_='foreignkey')
    op.drop_constraint('seats_shift3_student_id_fkey', 'seats', type_='foreignkey')
    op.drop_constraint('seats_shift1_student_id_fkey', 'seats', type_='foreignkey')
    op.drop_constraint('seats_library_id_fkey', 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_shift2_student_id_fkey'), 'seats', 'students', ['shift2_student_id'], ['id'])
    op.create_foreign_key(op.f('seats_shift3_student_id_fkey'), 'seats', 'students', ['shift3_student_id'], ['id'])
    op.create_foreign_key(op.f('seats_library_id_fkey'), 'seats', 'libraries', ['library_id'], ['id'])
    op.create_foreign_key(op.f('seats_shift1_student_id_fkey'), 'seats', 'students', ['shift1_student_id'], ['id'])
    op.drop_index(op.f('ix_seats_shift3_student_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_shift2_student_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_shift1_student_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_seat_number'), table_name='seats')
    op.drop_index(op.f('ix_seats_library_id'), table_name='seats')
    op.drop_index('idx_seats_library_number', table_name='seats')
    op.drop_constraint('monthly_payments_student_id_fkey', 'monthly_payments', type_='foreignkey')
    op.drop_constraint('monthly_payments_library_id_fkey', 'monthly_payments', type_='foreignkey')
    op.create_foreign_key(op.f('monthly_payments_library_id_fkey'), 'monthly_payments', 'libraries', ['library_id'], ['id'])
    op.create_foreign_key(op.f('monthly_payments_student_id_fkey'), 'monthly_payments', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_monthly_payments_student_id'), table_name='monthly_payments')
    op.drop_index(op.f('ix_monthly_payments_paid'), table_name='monthly_payments')
    op.drop_index(op.f('ix_monthly_payments_library_id'), table_name='monthly_payments')
    op.drop_index('idx_payments_student_month', table_name='monthly_payments')
    op.drop_index('idx_payments_library_paid', table_name='monthly_payments')
    op.drop_index('idx_payments_library_month', table_name='monthly_payments')
    op.alter_column('monthly_payments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_libraries_name'), table_name='libraries')
    op.drop_constraint('admins_library_id_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(op.f('admins_library_id_fkey'), 'admins', 'libraries', ['library_id'], ['id'])
    op.drop_index(op.f('ix_admins_status'), table_name='admins')
    op.drop_index(op.f('ix_admins_role'), table_name='admins')
    op.drop_index(op.f('ix_admins_library_id'), table_name='admins')
    # ### end Alembic commands ###
