"""Add monthly expenses table

Revision ID: 4f4412e07997
Revises: 42b2dd45c406
Create Date: 2025-08-02 21:01:40.224468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4412e07997'
down_revision: Union[str, Sequence[str], None] = '42b2dd45c406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_expenses_id'), 'monthly_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_expenses_library_id'), 'monthly_expenses', ['library_id'], unique=False)
    op.create_index(op.f('ix_monthly_expenses_month'), 'monthly_expenses', ['month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_expenses_month'), table_name='monthly_expenses')
    op.drop_index(op.f('ix_monthly_expenses_library_id'), table_name='monthly_expenses')
    op.drop_index(op.f('ix_monthly_expenses_id'), table_name='monthly_expenses')
    op.drop_table('monthly_expenses')
    # ### end Alembic commands ###
